CREATE SCHEMA dbc;

CREATE TABLE dbc.dbc_achievement
(
    id                    int4 DEFAULT 0 NOT NULL,
    faction               int4 DEFAULT 0 NOT NULL,
    instance_id           int4 DEFAULT 0 NOT NULL,
    supercedes            int4 DEFAULT 0 NOT NULL,
    title_lang_enus       text NULL,
    title_lang_engb       text NULL,
    title_lang_kokr       text NULL,
    title_lang_frfr       text NULL,
    title_lang_dede       text NULL,
    title_lang_encn       text NULL,
    title_lang_zhcn       text NULL,
    title_lang_entw       text NULL,
    title_lang_zhtw       text NULL,
    title_lang_eses       text NULL,
    title_lang_esmx       text NULL,
    title_lang_ruru       text NULL,
    title_lang_ptpt       text NULL,
    title_lang_ptbr       text NULL,
    title_lang_itit       text NULL,
    title_lang_unk        text NULL,
    title_lang_mask       int8 DEFAULT 0 NOT NULL,
    description_lang_enus text NULL,
    description_lang_engb text NULL,
    description_lang_kokr text NULL,
    description_lang_frfr text NULL,
    description_lang_dede text NULL,
    description_lang_encn text NULL,
    description_lang_zhcn text NULL,
    description_lang_entw text NULL,
    description_lang_zhtw text NULL,
    description_lang_eses text NULL,
    description_lang_esmx text NULL,
    description_lang_ruru text NULL,
    description_lang_ptpt text NULL,
    description_lang_ptbr text NULL,
    description_lang_itit text NULL,
    description_lang_unk  text NULL,
    description_lang_mask int8 DEFAULT 0 NOT NULL,
    category              int4 DEFAULT 0 NOT NULL,
    points                int4 DEFAULT 0 NOT NULL,
    ui_order              int4 DEFAULT 0 NOT NULL,
    flags                 int4 DEFAULT 0 NOT NULL,
    iconid                int4 DEFAULT 0 NOT NULL,
    reward_lang_enus      text NULL,
    reward_lang_engb      text NULL,
    reward_lang_kokr      text NULL,
    reward_lang_frfr      text NULL,
    reward_lang_dede      text NULL,
    reward_lang_encn      text NULL,
    reward_lang_zhcn      text NULL,
    reward_lang_entw      text NULL,
    reward_lang_zhtw      text NULL,
    reward_lang_eses      text NULL,
    reward_lang_esmx      text NULL,
    reward_lang_ruru      text NULL,
    reward_lang_ptpt      text NULL,
    reward_lang_ptbr      text NULL,
    reward_lang_itit      text NULL,
    reward_lang_unk       text NULL,
    reward_lang_mask      int8 DEFAULT 0 NOT NULL,
    minimum_criteria      int4 DEFAULT 0 NOT NULL,
    shares_criteria       int4 DEFAULT 0 NOT NULL,
    CONSTRAINT pk_dbc_achievement PRIMARY KEY (id)
);

INSERT INTO dbc.dbc_achievement (id, faction, instance_id, supercedes, title_lang_enus, title_lang_engb, title_lang_kokr, title_lang_frfr, title_lang_dede, title_lang_encn, title_lang_zhcn, title_lang_entw, title_lang_zhtw, title_lang_eses, title_lang_esmx, title_lang_ruru, title_lang_ptpt, title_lang_ptbr, title_lang_itit, title_lang_unk, title_lang_mask, description_lang_enus, description_lang_engb, description_lang_kokr, description_lang_frfr, description_lang_dede, description_lang_encn, description_lang_zhcn, description_lang_entw, description_lang_zhtw, description_lang_eses, description_lang_esmx, description_lang_ruru, description_lang_ptpt, description_lang_ptbr, description_lang_itit, description_lang_unk, description_lang_mask, category, points, ui_order, flags, iconid, reward_lang_enus, reward_lang_engb, reward_lang_kokr, reward_lang_frfr, reward_lang_dede, reward_lang_encn, reward_lang_zhcn, reward_lang_entw, reward_lang_zhtw, reward_lang_eses, reward_lang_esmx, reward_lang_ruru, reward_lang_ptpt, reward_lang_ptbr, reward_lang_itit, reward_lang_unk, reward_lang_mask, minimum_criteria, shares_criteria) VALUES(6, -1, -1, 0, 'Level 10', 'Level 10', '10 레벨', 'Niveau 10', 'Stufe 10', '10级', '10级', '10級', '10級', 'Nivel 10', 'Nivel 10', '10-й уровень', '', '', '', '', 16712190, 'Reach level 10.', 'Reach level 10.', '10 레벨 달성', 'Atteindre le niveau 10.', 'Erreicht Stufe 10.', '升到10级。', '升到10级。', '達到10級。', '達到10級。', 'Alcanza el nivel 10.', 'Alcanza el nivel 10.', 'Достигните 10-го уровня.', '', '', '', '', 16712190, 92, 10, 1, 4, 3268, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712174, 0, 0);

CREATE TABLE dbc.dbc_achievement_criteria
(
    id                    serial4        NOT NULL,
    achievement_id        int4 DEFAULT 0 NOT NULL,
    "type"                int4 DEFAULT 0 NOT NULL,
    asset_id              int4 DEFAULT 0 NOT NULL,
    quantity              int4 DEFAULT 0 NOT NULL,
    start_event           int4 DEFAULT 0 NOT NULL,
    start_asset           int4 DEFAULT 0 NOT NULL,
    fail_event            int4 DEFAULT 0 NOT NULL,
    fail_asset            int4 DEFAULT 0 NOT NULL,
    description_lang_enus text NULL,
    description_lang_engb text NULL,
    description_lang_kokr text NULL,
    description_lang_frfr text NULL,
    description_lang_dede text NULL,
    description_lang_encn text NULL,
    description_lang_zhcn text NULL,
    description_lang_entw text NULL,
    description_lang_zhtw text NULL,
    description_lang_eses text NULL,
    description_lang_esmx text NULL,
    description_lang_ruru text NULL,
    description_lang_ptpt text NULL,
    description_lang_ptbr text NULL,
    description_lang_itit text NULL,
    description_lang_unk  text NULL,
    description_lang_mask int4 DEFAULT 0 NOT NULL,
    flags                 int4 DEFAULT 0 NOT NULL,
    timer_start_event     int4 DEFAULT 0 NOT NULL,
    timer_asset_id        int4 DEFAULT 0 NOT NULL,
    timer_time            int4 DEFAULT 0 NOT NULL,
    ui_order              int4 DEFAULT 0 NOT NULL,
    CONSTRAINT dbc_achievement_criteria_pkey PRIMARY KEY (id)
);

CREATE TABLE dbc.dbc_areagroup
(
    id         int4 DEFAULT 0 NOT NULL,
    areaid_1   int4 DEFAULT 0 NOT NULL,
    areaid_2   int4 DEFAULT 0 NOT NULL,
    areaid_3   int4 DEFAULT 0 NOT NULL,
    areaid_4   int4 DEFAULT 0 NOT NULL,
    areaid_5   int4 DEFAULT 0 NOT NULL,
    areaid_6   int4 DEFAULT 0 NOT NULL,
    nextareaid int4 DEFAULT 0 NOT NULL,
    CONSTRAINT dbc_areagroup_pkey PRIMARY KEY (id)
);

CREATE TABLE dbc.dbc_areatable
(
    id                             serial4          NOT NULL,
    continent_id                   int4   DEFAULT 0 NOT NULL,
    parent_area_id                 int4   DEFAULT 0 NOT NULL,
    area_bit                       int4   DEFAULT 0 NOT NULL,
    flags                          int4   DEFAULT 0 NOT NULL,
    sound_provider_pref            int4   DEFAULT 0 NOT NULL,
    sound_provider_pref_underwater int4   DEFAULT 0 NOT NULL,
    ambience_id                    int4   DEFAULT 0 NOT NULL,
    zone_music                     int4   DEFAULT 0 NOT NULL,
    intro_sound                    int4   DEFAULT 0 NOT NULL,
    exploration_level              int4   DEFAULT 0 NOT NULL,
    area_name_lang_enus            text NULL,
    area_name_lang_engb            text NULL,
    area_name_lang_kokr            text NULL,
    area_name_lang_frfr            text NULL,
    area_name_lang_dede            text NULL,
    area_name_lang_encn            text NULL,
    area_name_lang_zhcn            text NULL,
    area_name_lang_entw            text NULL,
    area_name_lang_zhtw            text NULL,
    area_name_lang_eses            text NULL,
    area_name_lang_esmx            text NULL,
    area_name_lang_ruru            text NULL,
    area_name_lang_ptpt            text NULL,
    area_name_lang_ptbr            text NULL,
    area_name_lang_itit            text NULL,
    area_name_lang_unk             text NULL,
    area_name_lang_mask            int4   DEFAULT 0 NOT NULL,
    faction_group_mask             int4   DEFAULT 0 NOT NULL,
    liquid_type_id_1               int4   DEFAULT 0 NOT NULL,
    liquid_type_id_2               int4   DEFAULT 0 NOT NULL,
    liquid_type_id_3               int4   DEFAULT 0 NOT NULL,
    liquid_type_id_4               int4   DEFAULT 0 NOT NULL,
    min_elevation                  float4 DEFAULT 0 NOT NULL,
    ambient_multiplier             float4 DEFAULT 0 NOT NULL,
    lightid                        int4   DEFAULT 0 NOT NULL,
    CONSTRAINT dbc_areatable_pkey PRIMARY KEY (id)
);

CREATE TABLE dbc.dbc_areatrigger
(
    id           int4   DEFAULT 0 NOT NULL,
    continent_id int4   DEFAULT 0 NOT NULL,
    x            float4 DEFAULT 0 NOT NULL,
    y            float4 DEFAULT 0 NOT NULL,
    z            float4 DEFAULT 0 NOT NULL,
    radius       float4 DEFAULT 0 NOT NULL,
    box_length   float4 DEFAULT 0 NOT NULL,
    box_width    float4 DEFAULT 0 NOT NULL,
    box_height   float4 DEFAULT 0 NOT NULL,
    box_yaw      float4 DEFAULT 0 NOT NULL,
    CONSTRAINT dbc_areatrigger_pkey PRIMARY KEY (id)
);